FROM jenkins/jenkins:lts
LABEL Farrar142 "gksdjf1690@gmail.com"
USER root
RUN apt-get update \
    && apt-get install wget \
    && apt-get install git -y \
    && apt-get install apt-utils \
    && wget -qO- http://get.docker.com/ | sh \
    && curl -L "https://github.com/docker/compose/releases/download/1.24.1/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose \
    && chmod +x /usr/local/bin/docker-compose \
    && ln -s /usr/local/bin/docker-compose /usr/bin/docker-compose \
    && usermod -aG docker jenkins \
    && apt-get install python3 -y \
    && apt-get install pip -y
    ##